app:
  checkpointUrl: vendor/checkpoints/drums_rnn
  soundfontUrl: vendor/soundfonts/dmx/
  lang: fr
  theme: dark
  # Number of loops after which, unless there is user input, the drum machine will stop.
  maxIdleLoops: 8
  # Number of seconds after which, unless there is user input or the drum machine is playing,
  # the drum machine will be cleared.
  idleClearSeconds: 30
